# Site Settings
title: Hritwik Ekade
email: ekadehritwik@gmail.com
description: > # This description appears in your browser tab/search results
  M.I.S.M. Candidate at CMU and Technology Consultant specializing in full-stack 
  development, data optimization, and driving data-driven insights for large-scale enterprise systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://HritwikEkade.github.io" # the base hostname & protocol for your site
timezone: America/New_York

# Theme Settings (If using a Jekyll Theme)
# If you are using the Forty theme, make sure to add this line or similar:
# remote_theme: andrewbanchich/forty-jekyll-theme 

# Contact Details
github_username: HritwikEkade
linkedin_username: hritwikekade
scholar_google: https://scholar.google.com/citations?user=xHO1YY8AAAAJ&hl=en # Custom field for Google Scholar
phone: "+1 (412) 339-7388"
address: "Pittsburgh, PA"

# Additional Features
# Example for Forty: Set which content to show on the tiles
# tiles-source: 'posts' # Set to 'pages' if you create portfolio sections as pages

# Build settings
markdown: kramdown
permalink: pretty
# OR sometimes this is required for external themes
# Temporarily remove or comment out:
# remote_theme: andrewbanchich/forty-jekyll-theme 

# Use a highly-rated, responsive single-page portfolio theme
remote_theme: dops-m/resume-theme

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
